[project]
name = "newt-cli"
version = "0.2.0"
description = "A simple cli supposed to compliment fastapi development."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.20.0",
    "alembic>=1.8.0",
]

[project.scripts]
newt = "newt.main:app"
